# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/osboxes/Desktop/trabGrauA-SisopII/graua-skel

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/osboxes/Desktop/trabGrauA-SisopII/graua-skel

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"bin\" \"dev\" \"shlib\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/osboxes/Desktop/trabGrauA-SisopII/graua-skel/CMakeFiles /home/osboxes/Desktop/trabGrauA-SisopII/graua-skel/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/osboxes/Desktop/trabGrauA-SisopII/graua-skel/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named thread

# Build rule for target.
thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 thread
.PHONY : thread

# fast build rule for target.
thread/fast:
	$(MAKE) -f libthread/CMakeFiles/thread.dir/build.make libthread/CMakeFiles/thread.dir/build
.PHONY : thread/fast

#=============================================================================
# Target rules for targets named phil_1

# Build rule for target.
phil_1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phil_1
.PHONY : phil_1

# fast build rule for target.
phil_1/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/phil_1.dir/build.make grau_a_eval/CMakeFiles/phil_1.dir/build
.PHONY : phil_1/fast

#=============================================================================
# Target rules for targets named phil_2

# Build rule for target.
phil_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phil_2
.PHONY : phil_2

# fast build rule for target.
phil_2/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/phil_2.dir/build.make grau_a_eval/CMakeFiles/phil_2.dir/build
.PHONY : phil_2/fast

#=============================================================================
# Target rules for targets named phil_3

# Build rule for target.
phil_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phil_3
.PHONY : phil_3

# fast build rule for target.
phil_3/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/phil_3.dir/build.make grau_a_eval/CMakeFiles/phil_3.dir/build
.PHONY : phil_3/fast

#=============================================================================
# Target rules for targets named phil_4

# Build rule for target.
phil_4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phil_4
.PHONY : phil_4

# fast build rule for target.
phil_4/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/phil_4.dir/build.make grau_a_eval/CMakeFiles/phil_4.dir/build
.PHONY : phil_4/fast

#=============================================================================
# Target rules for targets named phil_5

# Build rule for target.
phil_5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phil_5
.PHONY : phil_5

# fast build rule for target.
phil_5/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/phil_5.dir/build.make grau_a_eval/CMakeFiles/phil_5.dir/build
.PHONY : phil_5/fast

#=============================================================================
# Target rules for targets named prod_cons

# Build rule for target.
prod_cons: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prod_cons
.PHONY : prod_cons

# fast build rule for target.
prod_cons/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/prod_cons.dir/build.make grau_a_eval/CMakeFiles/prod_cons.dir/build
.PHONY : prod_cons/fast

#=============================================================================
# Target rules for targets named prod_cons_condvar

# Build rule for target.
prod_cons_condvar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prod_cons_condvar
.PHONY : prod_cons_condvar

# fast build rule for target.
prod_cons_condvar/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/prod_cons_condvar.dir/build.make grau_a_eval/CMakeFiles/prod_cons_condvar.dir/build
.PHONY : prod_cons_condvar/fast

#=============================================================================
# Target rules for targets named prod_cons_yielding

# Build rule for target.
prod_cons_yielding: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prod_cons_yielding
.PHONY : prod_cons_yielding

# fast build rule for target.
prod_cons_yielding/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/prod_cons_yielding.dir/build.make grau_a_eval/CMakeFiles/prod_cons_yielding.dir/build
.PHONY : prod_cons_yielding/fast

#=============================================================================
# Target rules for targets named rw_locks

# Build rule for target.
rw_locks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rw_locks
.PHONY : rw_locks

# fast build rule for target.
rw_locks/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/rw_locks.dir/build.make grau_a_eval/CMakeFiles/rw_locks.dir/build
.PHONY : rw_locks/fast

#=============================================================================
# Target rules for targets named sanity_joiner

# Build rule for target.
sanity_joiner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sanity_joiner
.PHONY : sanity_joiner

# fast build rule for target.
sanity_joiner/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/sanity_joiner.dir/build.make grau_a_eval/CMakeFiles/sanity_joiner.dir/build
.PHONY : sanity_joiner/fast

#=============================================================================
# Target rules for targets named sanity_recursion

# Build rule for target.
sanity_recursion: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sanity_recursion
.PHONY : sanity_recursion

# fast build rule for target.
sanity_recursion/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/sanity_recursion.dir/build.make grau_a_eval/CMakeFiles/sanity_recursion.dir/build
.PHONY : sanity_recursion/fast

#=============================================================================
# Target rules for targets named sanity_stack

# Build rule for target.
sanity_stack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sanity_stack
.PHONY : sanity_stack

# fast build rule for target.
sanity_stack/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/sanity_stack.dir/build.make grau_a_eval/CMakeFiles/sanity_stack.dir/build
.PHONY : sanity_stack/fast

#=============================================================================
# Target rules for targets named test1

# Build rule for target.
test1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test1
.PHONY : test1

# fast build rule for target.
test1/fast:
	$(MAKE) -f grau_a_eval/CMakeFiles/test1.dir/build.make grau_a_eval/CMakeFiles/test1.dir/build
.PHONY : test1/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... thread"
	@echo "... phil_1"
	@echo "... phil_2"
	@echo "... phil_3"
	@echo "... phil_4"
	@echo "... phil_5"
	@echo "... prod_cons"
	@echo "... prod_cons_condvar"
	@echo "... prod_cons_yielding"
	@echo "... rw_locks"
	@echo "... sanity_joiner"
	@echo "... sanity_recursion"
	@echo "... sanity_stack"
	@echo "... test1"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

